### ISSUE TITLE
user_pad crashes when creating new user

### ISSUE THREAD

**Issue by loadavg** [aoberegg/ep_user_pad#8]
When I create a new user on my home page at www.editopia.com etherpad crashes as follows:

[2014-07-07 10:29:52.493] [ERROR] console - ep_user_pad_frontend: existValueInDatabase error, sql: SELECT \* from User where User.name = ?
[2014-07-07 10:29:52.533] [ERROR] console - Error: Cannot find module 'encoding'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/nodemailer/node_modules/mailcomposer/node_modules/mimelib/lib/mimelib.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[2014-07-07 10:29:52.533] [INFO] console - graceful shutdown...
[2014-07-07 10:29:52.534] [INFO] console - db sucessfully closed.

I dont see notes on editing the database anywhere ? I am using a mysql database and free pads work fine..

http://editopia.com/public_pad/testpad

also how do i install module encoding ?

also..

How can I support this project ? looking to launch a proper etherpad driven site at editopia here...

thanks!

**Comment by niraj8241** [comment]
If anyone faced issues setting up databases. Please copy paste the below ones.

CREATE TABLE IF NOT EXISTS GroupPads (
 GroupID int(11) NOT NULL,
 PadName varchar(255) COLLATE utf8_bin NOT NULL,
 PRIMARY KEY (GroupID,PadName)
 );


 CREATE TABLE IF NOT EXISTS Groups ( groupID int(11) NOT NULL AUTO_INCREMENT, name varchar(255) COLLATE utf8_bin NOT NULL DEFAULT , PRIMARY KEY (groupID,name) );


 CREATE TABLE IF NOT EXISTS NotRegisteredUsersGroups ( email varchar(255) NOT NULL, groupID int(11) NOT NULL );

 CREATE TABLE IF NOT EXISTS User (
userID int(11) NOT NULL AUTO_INCREMENT,
name varchar(255) COLLATE utf8_bin NOT NULL DEFAULT ,
pwd varchar(255) COLLATE utf8_bin DEFAULT NULL,
considered tinyint(11) DEFAULT NULL,
SSO tinyint(4) DEFAULT NULL,
FullName varchar(255) COLLATE utf8_bin DEFAULT NULL,
considerationString varchar(50) COLLATE utf8_bin DEFAULT NULL,
salt varchar(255) COLLATE utf8_bin DEFAULT NULL,
active int(1) DEFAULT NULL,
PRIMARY KEY (userID, name)
);


CREATE TABLE IF NOT EXISTS UserGroup (userID int(11) NOT NULL DEFAULT 0, groupID int(11) NOT NULL DEFAULT 0, Role int(11) DEFAULT NULL, PRIMARY KEY (userID,groupID) );
