### ISSUE TITLE
Etherpad Crashes (Login, or Group Managment)

### ISSUE THREAD

**Issue by Zeitalter** [aoberegg/ep_user_pad#9]
Hey,

When I log in Etherpad crashes with the following error message:

->
[2014-12-17 10:49:59.192] [ERROR] console - ReferenceError: fileName is not defined
    at Query.mySqlErrorHandler (/home/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/hooks.js:42:9)
    at Query.emit (events.js:117:20)
    at Query.Sequence.end (/home/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/sequences/Sequence.js:70:12)
    at Query.ErrorPacket (/home/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/home/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/Protocol.js:172:24)
    at Parser.write (/home/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/home/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.ondata (stream.js:51:26)
    at Socket.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:764:14)
<-

Can anyone help me ?

sry for my bad english :)
grettings Lyca

**Comment by marrngtn** [comment]
Ditto Same Problem..........
![ep_user_pad](https://cloud.githubusercontent.com/assets/4671311/7738719/8fb7378a-ff25-11e4-88ae-b5f28cf1fc75.PNG)

**Comment by rebborodin** [comment]
Maybe this is a Problem with your configuration of the DB. What helped me was, in the 'mySqlhandler' - function to add on top:
`log('error', 'mySqlHandler: ' + err);
This displayed the complete path of the error.
